
#[derive(Debug)]
pub enum CallingConv { 
    AmdgpuCs,
    AmdgpuEs,
    AmdgpuGs,
    AmdgpuHs,
    AmdgpuKernel,
    AmdgpuLs,
    AmdgpuPs,
    AmdgpuVs,
    AnyregCc,
    ArmAapcsVfpcc,
    ArmAapcscc,
    ArmApcscc,
    AvrIntrcc,
    AvrSignalcc,
    Coldcc,
    CxxFastTlscc,
    FastCc,
    GhCcc,
    HhvmCcc,
    HhvmCc,
    IntelOclBicc,
    Msp430Intrcc,
    PreserveAllcc,
    PreserveMostcc,
    PtxDevice,
    PtxKernel,
    SpirFunc,
    SpirKernel,
    Swiftcc,
    WebkitJscc,
    Win64cc,
    X8664Sysvcc,
    X86Fastcallcc,
    X86Intrcc,
    X86Regcallcc,
    X86Stdcallcc,
    X86Thiscallcc,
    X86Vectorcallcc,
    Ccc,
	Cc {
        int: u32
    },
}